{
 "title": "redis-session-store",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Unique Sessions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_sessions_unique_sessions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Median Session Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_session_size_quantiles{quantile=\"0.5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Largest Session",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_session_largest{sessionRank=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Local Cache Sizes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 0 },
   "targets": [
    { "expr": "redis_local_cache_num_entries", "legendFormat": "num entries" },
    {
     "expr": "redis_local_cache_average_entry_size",
     "legendFormat": "average size"
    }
   ]
  },
  {
   "title": "Session size stats",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "targets": [
    { "expr": "redis_session_size_quantiles", "legendFormat": "Quantile {{quantile}}" }
   ]
  },
  {
   "title": "Most Accessed Sessions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 6 },
   "targets": [
    {
     "expr": "redis_session_most_accessed{sessionRank=\"1\"}",
     "legendFormat": "Most Accessed Session"
    },
    {
     "expr": "redis_session_most_accessed{sessionRank=\"2\"}",
     "legendFormat": "Second Most Accessed Session"
    },
    {
     "expr": "redis_session_most_accessed{sessionRank=\"3\"}",
     "legendFormat": "Third Most Accessed Session"
    },
    {
     "expr": "redis_session_most_accessed{sessionRank=\"4\"}",
     "legendFormat": "Fourth Most Accessed Session"
    },
    {
     "expr": "redis_session_most_accessed{sessionRank=\"5\"}",
     "legendFormat": "Fifth Most Accessed Session"
    }
   ]
  }
 ]
}